api_platform:
    show_webby: false
    mapping:
        paths:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/config/api/resources.yaml'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json: ['application/json']
        html: ['text/html']
        jsonld: ['application/ld+json']