version: '3.3'
services:
  phptest:
    build:
      context: ./tools/docker/php
    volumes:
      - .:/var/www:delegated
    links:
      - dbtest
    networks:
      - test
  dbtest:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5433:5433
    networks:
      - test

networks:
  test: